# Generated by Django 3.1.7 on 2021-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
