# Generated by Django 3.1.7 on 2021-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=16)),
                ('user_phone', models.CharField(max_length=11)),
                ('user_nickname', models.CharField(max_length=16, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
