# Generated by Django 3.1.7 on 2021-04-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SignUp',
        ),
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
