# Generated by Django 3.1.7 on 2021-04-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210403_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
