# Generated by Django 3.1.7 on 2021-04-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210404_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
