# Generated by Django 3.1.7 on 2021-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210404_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
