# Generated by Django 3.1.7 on 2021-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
