# Generated by Django 3.1.7 on 2021-04-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil',
            new_name='email',
        ),
    ]
