# Generated by Django 3.1.7 on 2021-04-04 05:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('number', phone_field.models.PhoneField(max_length=31)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
