# Generated by Django 3.1.7 on 2021-04-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user',
            new_name='username',
        ),
    ]
