# Generated by Django 3.1.7 on 2021-04-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='img',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
