# Generated by Django 3.1.7 on 2021-04-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feeds', '0002_auto_20210410_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
