# Generated by Django 3.1.7 on 2021-04-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'signin',
            },
        ),
    ]
