# Generated by Django 3.1.7 on 2021-04-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210404_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signin',
            new_name='UserInfo',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
